"""Turning minor units into something a person reads (D7 → shared on D9).

Every amount in this project is an integer number of minor units, from
`prices.amount_cents` through `orders.total_amount_cents` to Stripe's
`amount_total`, and nothing rounds anywhere along that path. This module is the
one place that stops being true, because a page and an assistant both have to
say `€94.99` rather than `18998`.

**It lives here rather than in the page that first needed it** because two
things now render money for a person, and they were rendering it differently:
`api/routers/checkout_pages.py` produced `42.00 EUR` while `agent/prompt.py`
taught the model to say `€42.00`. Two formats for one amount is the same class
of problem as two names for one number — the thing CLAUDE.md's
`amount_cents`/`price_cents` rule exists to stop — except that this pair is
seen by the *same shopper*, one in the chat and one on the payment page a
click later. So there is one function, and the assistant's own worked example
is generated by it rather than typed next to it.

A module at the top of the package rather than under `api/` or `agent/`,
because both import it and neither owns it. It pulls in nothing: no FastAPI,
no SDK, not even configuration.
"""

from __future__ import annotations

# Currencies whose smallest unit *is* the unit: no decimal part exists, so
# dividing by 100 would invent one. Not exhaustive — these are the ones a
# shop like this plausibly meets. Anything unlisted is treated as two decimals,
# which is right for every currency this project actually sells in.
ZERO_DECIMAL_CURRENCIES = frozenset(
    {"bif", "clp", "djf", "gnf", "jpy", "kmf", "krw", "mga", "pyg", "rwf",
     "ugx", "vnd", "vuv", "xaf", "xof", "xpf"}
)

# One entry, and it is meant to stay that way. The shop sells in one currency
# at a time — `CURRENCY` decides which — so this needs exactly the symbol for
# the currency in use, and everything else falls back to the ISO code, which is
# unambiguous and never wrong. Growing this into a table of every currency's
# symbol would be work in service of a shop that does not exist, and the first
# thing it would get wrong is placement: a symbol is not always a prefix, and
# several currencies share one. Add a line here when the shop adds a currency.
SYMBOLS = {"eur": "€"}


def format_amount(minor_units: int | None, currency: str | None) -> str:
    """Render an amount for a person to read.

    `4200 EUR` reads as four thousand to the shopper who just paid forty-two,
    which is why the conversion happens at all, and it happens here and nowhere
    else — the same boundary the `amount_cents` to `price_cents` rename
    crosses, for the same reason.

    Returns `€42.00` for a currency whose symbol is known and `42.00 USD` for
    one that is not, so an unfamiliar currency degrades to something correct
    rather than to something wrong. `None` is an em dash: an amount Stripe did
    not report is not zero.
    """
    if minor_units is None:
        return "—"

    code = (currency or "").lower()
    if code in ZERO_DECIMAL_CURRENCIES:
        amount = f"{minor_units:,}"
    else:
        amount = f"{minor_units / 100:,.2f}"

    symbol = SYMBOLS.get(code)
    return f"{symbol}{amount}" if symbol else f"{amount} {code.upper()}"
